package com.adresnokta.app;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.*; import android.graphics.drawable.*;
import android.net.*; import android.view.*; import android.widget.*; import org.json.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.*;

public class MainActivity extends Activity {
 final int BLUE=Color.rgb(20,120,242), TEXT=Color.rgb(15,35,70), MUTED=Color.rgb(90,110,140);
 LinearLayout root,form; TextView info; Spinner il,ilce,mahalle,sokak,bina; boolean lock=false;
 ArrayList<String> iller=new ArrayList<>(), ilceler=new ArrayList<>(), mahalleler=new ArrayList<>(), sokaklar=new ArrayList<>(), binalar=new ArrayList<>();
 String[] IL={"İl seçin","Adana","Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydın","Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır","Isparta","İstanbul","İzmir","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri","Kırıkkale","Kırklareli","Kırşehir","Kilis","Kocaeli","Konya","Kütahya","Malatya","Manisa","Mardin","Mersin","Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Siirt","Sinop","Sivas","Şanlıurfa","Şırnak","Tekirdağ","Tokat","Trabzon","Tunceli","Uşak","Van","Yalova","Yozgat","Zonguldak"};

 @Override public void onCreate(Bundle b){super.onCreate(b); build();}
 int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
 GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
 TextView txt(String s,int sp,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(TEXT);if(bold)t.setTypeface(null,Typeface.BOLD);return t;}
 void build(){
  ScrollView sv=new ScrollView(this); sv.setBackgroundColor(Color.rgb(248,250,253)); root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(20),dp(16),dp(24));sv.addView(root);
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);
  TextView pin=txt("●",30,true);pin.setTextColor(BLUE);head.addView(pin); LinearLayout ht=new LinearLayout(this);ht.setOrientation(LinearLayout.VERTICAL);ht.setPadding(16,0,0,0);
  ht.addView(txt("Adres Nokta",28,true)); TextView sub=txt("Türkiye için hızlı ve kademeli adres arama",14,false);sub.setTextColor(MUTED);ht.addView(sub);head.addView(ht);root.addView(head);
  form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(16),dp(16),dp(16),dp(16));form.setBackground(bg(Color.WHITE,28)); LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,-2);fp.setMargins(0,28,0,18);root.addView(form,fp);
  il=field("İl"); ilce=field("İlçe"); mahalle=field("Mahalle"); sokak=field("Sokak / Cadde"); bina=field("Bina Numarası");
  set(il,Arrays.asList(IL)); disable(ilce,"Önce il seçin");disable(mahalle,"Önce ilçe seçin");disable(sokak,"Önce mahalle seçin");disable(bina,"Önce sokak seçin");
  Button go=new Button(this);go.setText("⌕   ADRESİ GETİR");go.setTextColor(Color.WHITE);go.setTextSize(17);go.setTypeface(null,Typeface.BOLD);go.setBackground(bg(BLUE,20));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(56));bp.setMargins(0,22,0,0);form.addView(go,bp);
  info=txt("Seçimlere İl ile başlayın.",14,false);info.setTextColor(MUTED);root.addView(info);
  TextView osm=txt("Adres verisi © OpenStreetMap katkıda bulunanlar",12,false);osm.setTextColor(MUTED);osm.setPadding(0,30,0,0);root.addView(osm);
  il.setOnItemSelectedListener(listener(()->loadDistricts())); ilce.setOnItemSelectedListener(listener(()->loadNeighbourhoods())); mahalle.setOnItemSelectedListener(listener(()->loadStreets())); sokak.setOnItemSelectedListener(listener(()->loadNumbers()));
  go.setOnClickListener(v->resolve());
  setContentView(sv);
 }
 Spinner field(String label){TextView l=txt(label,15,true);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,12,0,6);form.addView(l,lp);Spinner s=new Spinner(this);s.setBackground(bg(Color.rgb(244,248,253),18));s.setPadding(16,0,12,0);form.addView(s,new LinearLayout.LayoutParams(-1,dp(52)));return s;}
 AdapterView.OnItemSelectedListener listener(Runnable r){return new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(!lock&&pos>0)r.run();}};}
 void set(Spinner s,List<String> x){lock=true;ArrayAdapter<String>a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,x);s.setAdapter(a);s.setEnabled(true);lock=false;}
 void disable(Spinner s,String hint){set(s,Arrays.asList(hint));s.setEnabled(false);}
 String val(Spinner s){return s.getSelectedItem()==null?"":s.getSelectedItem().toString();}
 void busy(String s){runOnUiThread(()->info.setText(s));}
 String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestProperty("User-Agent","AdresNokta/2.3 Android");c.setConnectTimeout(20000);c.setReadTimeout(30000);int code=c.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x);r.close();return b.toString();}
 String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}
 JSONObject addressTree(){
  try{InputStream in=getResources().openRawResource(com.adresnokta.app.R.raw.address_tree);BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String ln;while((ln=br.readLine())!=null)sb.append(ln);br.close();return new JSONObject(sb.toString());}catch(Exception e){return null;}
 }
 JSONObject cityNode(JSONObject tree,String city){
  if(tree==null)return null;Iterator<String> it=tree.keys();while(it.hasNext()){String k=it.next();if(k.equalsIgnoreCase(city))return tree.optJSONObject(k);}return null;
 }
 void loadDistricts(){String city=val(il);disable(ilce,"Yükleniyor…");disable(mahalle,"Önce ilçe seçin");disable(sokak,"Önce mahalle seçin");disable(bina,"Önce sokak seçin");try{JSONObject cn=cityNode(addressTree(),city);JSONObject ds=cn==null?null:cn.optJSONObject("ilceler");ArrayList<String> list=new ArrayList<>();list.add("İlçe seçin");if(ds!=null){ArrayList<String> names=new ArrayList<>();Iterator<String> it=ds.keys();while(it.hasNext())names.add(it.next());Collections.sort(names,new Comparator<String>(){public int compare(String a,String b){return java.text.Collator.getInstance(new Locale("tr","TR")).compare(a,b);}});list.addAll(names);}set(ilce,list);info.setText(list.size()>1?"İlçe seçin.":"Bu il için ilçe verisi bulunamadı.");}catch(Exception e){info.setText("Yerel ilçe verisi okunamadı.");}}
 void loadNeighbourhoods(){String city=val(il),district=val(ilce);disable(mahalle,"Yükleniyor…");disable(sokak,"Önce mahalle seçin");disable(bina,"Önce sokak seçin");try{JSONObject cn=cityNode(addressTree(),city);JSONObject ds=cn==null?null:cn.optJSONObject("ilceler");JSONArray ns=ds==null?null:ds.optJSONArray(district);ArrayList<String> list=new ArrayList<>();list.add("Mahalle seçin");if(ns!=null){ArrayList<String> names=new ArrayList<>();for(int i=0;i<ns.length();i++){String n=ns.optString(i);if(!n.isEmpty())names.add(n);}Collections.sort(names,new Comparator<String>(){public int compare(String a,String b){return java.text.Collator.getInstance(new Locale("tr","TR")).compare(a,b);}});list.addAll(names);}set(mahalle,list);info.setText(list.size()>1?"Mahalle seçin.":"Bu ilçe için mahalle verisi bulunamadı.");}catch(Exception e){info.setText("Yerel mahalle verisi okunamadı.");}}
 JSONObject geoArea()throws Exception{String place=val(mahalle)+", "+val(ilce)+", "+val(il)+", Türkiye";String nq="https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=tr&addressdetails=1&limit=5&q="+enc(place);JSONArray a=new JSONArray(get(nq));if(a.length()==0)throw new Exception("Mahalle bulunamadı");JSONObject best=a.getJSONObject(0);for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);String type=o.optString("type");if(type.equals("administrative")||type.equals("neighbourhood")||type.equals("quarter")||type.equals("suburb")){best=o;break;}}return best;}
 String overpass(String q)throws Exception{Exception last=null;String[] hosts={"https://overpass-api.de/api/interpreter?data=","https://overpass.kumi.systems/api/interpreter?data="};for(String h:hosts){try{return get(h+enc(q));}catch(Exception e){last=e;}}throw last==null?new Exception():last;}
 void loadStreets(){disable(sokak,"Yükleniyor…");disable(bina,"Önce sokak seçin");new Thread(()->{try{JSONObject p=geoArea();JSONArray bb=p.getJSONArray("boundingbox");String south=bb.getString(0),north=bb.getString(1),west=bb.getString(2),east=bb.getString(3);String q="[out:json][timeout:25];way("+south+","+west+","+north+","+east+")[highway][name];out tags;";JSONArray es=new JSONObject(overpass(q)).getJSONArray("elements");TreeSet<String> z=new TreeSet<>(java.text.Collator.getInstance(new Locale("tr","TR")));for(int i=0;i<es.length();i++){JSONObject t=es.getJSONObject(i).optJSONObject("tags");if(t!=null){String n=t.optString("name");if(!n.isEmpty())z.add(n);}}ArrayList<String> list=new ArrayList<>();list.add("Sokak / Cadde seçin");list.addAll(z);runOnUiThread(()->{set(sokak,list);info.setText(list.size()>1?list.size()-1+" sokak/cadde bulundu.":"Bu mahallede OSM sokak/cadde kaydı bulunamadı.");});}catch(Exception e){busy("Sokak/cadde verisi alınamadı. Tekrar deneyin.");}},"streets").start();}
 void loadNumbers(){String street=val(sokak).replace("\"","");disable(bina,"Yükleniyor…");new Thread(()->{try{JSONObject p=geoArea();JSONArray bb=p.getJSONArray("boundingbox");String south=bb.getString(0),north=bb.getString(1),west=bb.getString(2),east=bb.getString(3);String q="[out:json][timeout:25];nwr("+south+","+west+","+north+","+east+")[\"addr:housenumber\"][\"addr:street\"=\""+street+"\"];out tags center;";JSONArray es=new JSONObject(overpass(q)).getJSONArray("elements");TreeSet<String> z=new TreeSet<>(new Comparator<String>(){public int compare(String a,String b){try{return Integer.compare(Integer.parseInt(a.replaceAll("\\D.*","")),Integer.parseInt(b.replaceAll("\\D.*","")));}catch(Exception e){return a.compareToIgnoreCase(b);}}});for(int i=0;i<es.length();i++){JSONObject t=es.getJSONObject(i).optJSONObject("tags");if(t!=null){String n=t.optString("addr:housenumber");if(!n.isEmpty())z.add(n);}}ArrayList<String> list=new ArrayList<>();list.add("Bina numarası seçin");list.addAll(z);runOnUiThread(()->{set(bina,list);info.setText(list.size()>1?list.size()-1+" bina numarası bulundu.":"Bu sokakta OpenStreetMap bina numarası kaydı bulunamadı.");});}catch(Exception e){busy("Bina numarası verisi alınamadı. Tekrar deneyin.");}},"numbers").start();}
 void overpassNames(String q,Spinner target,String first,String what){new Thread(()->{try{JSONArray es=new JSONObject(get("https://overpass-api.de/api/interpreter?data="+enc(q))).getJSONArray("elements");TreeSet<String>z=new TreeSet<>();for(int i=0;i<es.length();i++){JSONObject t=es.getJSONObject(i).optJSONObject("tags");if(t!=null){String n=t.optString("name");if(!n.isEmpty())z.add(n);}}ArrayList<String>a=new ArrayList<>();a.add(first);a.addAll(z);runOnUiThread(()->{set(target,a);info.setText(a.size()>1?what+" seçin.":what+" verisi bulunamadı.");});}catch(Exception e){busy(what+" listesi alınamadı.");}}).start();}
 void resolve(){if(!bina.isEnabled()||bina.getSelectedItemPosition()==0){info.setText("Lütfen bina numarasına kadar seçim yapın.");return;}String address=val(bina)+" "+val(sokak)+", "+val(mahalle)+", "+val(ilce)+", "+val(il)+", Türkiye";busy("Adres doğrulanıyor…");new Thread(()->{try{String u="https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=tr&addressdetails=1&limit=1&street="+enc(val(bina)+" "+val(sokak))+"&city="+enc(val(ilce))+"&state="+enc(val(il));JSONArray a=new JSONArray(get(u));if(a.length()==0)throw new Exception();JSONObject o=a.getJSONObject(0);double lat=o.getDouble("lat"),lon=o.getDouble("lon");runOnUiThread(()->detail(address,lat,lon));}catch(Exception e){busy("Seçilen adres için koordinat bulunamadı.");}}).start();}
 void detail(String a,double lat,double lon){root.removeAllViews();TextView back=txt("‹   Adres Detayı",25,true);back.setPadding(0,12,0,25);back.setOnClickListener(v->build());root.addView(back);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(28,28,28,28);card.setBackground(bg(Color.WHITE,28));TextView pin=txt("●  "+a,19,true);pin.setTextColor(TEXT);card.addView(pin);TextView co=txt("\nKoordinatlar\n"+lat+", "+lon,15,false);co.setTextColor(MUTED);card.addView(co);Button map=new Button(this);map.setText("➤  GOOGLE MAPS'TE AÇ");map.setTextColor(Color.WHITE);map.setTextSize(16);map.setBackground(bg(BLUE,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,28,0,0);card.addView(map,p);map.setOnClickListener(v->nav(lat,lon));root.addView(card);}
 void nav(double lat,double lon){Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("google.navigation:q="+lat+","+lon+"&mode=d"));i.setPackage("com.google.android.apps.maps");try{startActivity(i);}catch(Exception e){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/dir/?api=1&destination="+lat+","+lon)));}}
}
